language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
  - sudo wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - sudo gunzip GeoLiteCity.dat.gz
  - sudo mv GeoLiteCity.dat /usr/local/share/GeoIP/GeoIPCity.dat
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-geoip/.travis_build_config.rb build_config.rb
script:
  - make all test
